/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Alexis Salvador
 */
public class PantallaMenuGerente extends javax.swing.JFrame {

    /**
     * Creates new form PantallaMenuMesero
     */
    public PantallaMenuGerente() {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/icon_cafezito.png"));
        setIconImage(icon);
        DialogoPregunta.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogoPregunta = new javax.swing.JDialog(this,true);
        jPanel7 = new javax.swing.JPanel();
        LblPreguntaensaje = new javax.swing.JLabel();
        BtnActualizarno = new javax.swing.JButton();
        BtnActualizarsi = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        BtnModificarEmpleado = new javax.swing.JButton();
        BtnRegistrarEmpleado = new javax.swing.JButton();
        BtnCerrarSesionGestEmpleado = new javax.swing.JButton();
        BtnGestionarMenu = new javax.swing.JButton();
        BtnRegistroEgresos = new javax.swing.JButton();
        jLabel77 = new javax.swing.JLabel();

        DialogoPregunta.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        DialogoPregunta.setTitle("Mensaje de confirmación");
        DialogoPregunta.setBackground(new java.awt.Color(47, 20, 0));
        DialogoPregunta.setBounds(new java.awt.Rectangle(0, 0, 387, 152));
        DialogoPregunta.setMinimumSize(new java.awt.Dimension(360, 152));
        DialogoPregunta.setResizable(false);

        jPanel7.setBackground(new java.awt.Color(47, 20, 0));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204), 2));
        jPanel7.setMinimumSize(new java.awt.Dimension(362, 145));

        LblPreguntaensaje.setFont(new java.awt.Font("AppleGothic", 0, 16)); // NOI18N
        LblPreguntaensaje.setForeground(new java.awt.Color(255, 255, 102));
        LblPreguntaensaje.setText("¿Desea Cerrar su Sesión?");

        BtnActualizarno.setBackground(new java.awt.Color(255, 255, 153));
        BtnActualizarno.setFont(new java.awt.Font("AppleGothic", 0, 16)); // NOI18N
        BtnActualizarno.setForeground(new java.awt.Color(47, 20, 0));
        BtnActualizarno.setText("No");

        BtnActualizarsi.setBackground(new java.awt.Color(255, 255, 153));
        BtnActualizarsi.setFont(new java.awt.Font("AppleGothic", 0, 16)); // NOI18N
        BtnActualizarsi.setForeground(new java.awt.Color(47, 20, 0));
        BtnActualizarsi.setText("Si");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/question.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addGap(43, 43, 43)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(BtnActualizarsi, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(BtnActualizarno, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LblPreguntaensaje))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(LblPreguntaensaje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnActualizarno)
                            .addComponent(BtnActualizarsi))))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DialogoPreguntaLayout = new javax.swing.GroupLayout(DialogoPregunta.getContentPane());
        DialogoPregunta.getContentPane().setLayout(DialogoPreguntaLayout);
        DialogoPreguntaLayout.setHorizontalGroup(
            DialogoPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DialogoPreguntaLayout.setVerticalGroup(
            DialogoPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogoPreguntaLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu Gerente");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnModificarEmpleado.setBackground(new java.awt.Color(255, 255, 153));
        BtnModificarEmpleado.setFont(new java.awt.Font("AppleGothic", 1, 14)); // NOI18N
        BtnModificarEmpleado.setForeground(new java.awt.Color(51, 0, 0));
        BtnModificarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user-7.png"))); // NOI18N
        BtnModificarEmpleado.setText("Modificar Empleado");
        BtnModificarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnModificarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 250, 70));

        BtnRegistrarEmpleado.setBackground(new java.awt.Color(255, 255, 153));
        BtnRegistrarEmpleado.setFont(new java.awt.Font("AppleGothic", 1, 14)); // NOI18N
        BtnRegistrarEmpleado.setForeground(new java.awt.Color(51, 0, 0));
        BtnRegistrarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user-3.png"))); // NOI18N
        BtnRegistrarEmpleado.setText("Registrar Empleado");
        getContentPane().add(BtnRegistrarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 250, 70));

        BtnCerrarSesionGestEmpleado.setBackground(new java.awt.Color(255, 255, 153));
        BtnCerrarSesionGestEmpleado.setFont(new java.awt.Font("AppleGothic", 0, 18)); // NOI18N
        BtnCerrarSesionGestEmpleado.setForeground(new java.awt.Color(51, 0, 0));
        BtnCerrarSesionGestEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit.png"))); // NOI18N
        BtnCerrarSesionGestEmpleado.setText("Cerrar Sesión");
        BtnCerrarSesionGestEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarSesionGestEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCerrarSesionGestEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 220, 60));

        BtnGestionarMenu.setBackground(new java.awt.Color(255, 255, 153));
        BtnGestionarMenu.setFont(new java.awt.Font("AppleGothic", 1, 14)); // NOI18N
        BtnGestionarMenu.setForeground(new java.awt.Color(51, 0, 0));
        BtnGestionarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu-2.png"))); // NOI18N
        BtnGestionarMenu.setText("Gestionar Menú");
        getContentPane().add(BtnGestionarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 260, 70));

        BtnRegistroEgresos.setBackground(new java.awt.Color(255, 255, 153));
        BtnRegistroEgresos.setFont(new java.awt.Font("AppleGothic", 1, 14)); // NOI18N
        BtnRegistroEgresos.setForeground(new java.awt.Color(51, 0, 0));
        BtnRegistroEgresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/money-2.png"))); // NOI18N
        BtnRegistroEgresos.setText("Registrar Egresos");
        getContentPane().add(BtnRegistroEgresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 260, 70));

        jLabel77.setFont(new java.awt.Font("AppleGothic", 1, 14)); // NOI18N
        jLabel77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MenuG.jpg"))); // NOI18N
        getContentPane().add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCerrarSesionGestEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarSesionGestEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCerrarSesionGestEmpleadoActionPerformed

    private void BtnModificarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnModificarEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaMenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaMenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaMenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaMenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaMenuGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnActualizarno;
    public javax.swing.JButton BtnActualizarsi;
    public javax.swing.JButton BtnCerrarSesionGestEmpleado;
    public javax.swing.JButton BtnGestionarMenu;
    public javax.swing.JButton BtnModificarEmpleado;
    public javax.swing.JButton BtnRegistrarEmpleado;
    public javax.swing.JButton BtnRegistroEgresos;
    public javax.swing.JDialog DialogoPregunta;
    public javax.swing.JLabel LblPreguntaensaje;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel77;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
