/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Alexis Salvador
 */
public class PantallaAgregarAlaOrden extends javax.swing.JFrame {

    /**
     * Creates new form PantallaAgregarAlaOrden
     */
    public PantallaAgregarAlaOrden() {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/icon_cafezito.png"));
        setIconImage(icon);
        DialogoMensajeError.setLocationRelativeTo(null);
        DialogoMensajeExito.setLocationRelativeTo(null);
        DialogoMensajeExito.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogoMensajeExito = new javax.swing.JDialog(this,true);
        jPanel3 = new javax.swing.JPanel();
        LblMensajeConfirmacion = new javax.swing.JLabel();
        BtnAceptarMensajeExito = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        DialogoMensajeError = new javax.swing.JDialog(this,true);
        jPanel6 = new javax.swing.JPanel();
        LbllMensajeError = new javax.swing.JLabel();
        BtnAceptarMensajeErrores = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        SpinnerCantidadCodMenu = new javax.swing.JSpinner();
        TxtCodigoMenu = new javax.swing.JTextField();
        BtnAgregarCodigoMenu = new javax.swing.JButton();
        jPanel27 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        SpinnerCantidadPlatillo = new javax.swing.JSpinner();
        BtnAgregarPlatillo = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        CbxPlatillo = new javax.swing.JComboBox<>();
        CbxPostre = new javax.swing.JComboBox<>();
        CbxBebida = new javax.swing.JComboBox<>();
        SpinnerCantidadBebida = new javax.swing.JSpinner();
        SpinnerCantidadPostre = new javax.swing.JSpinner();
        BtnAgregarPostre = new javax.swing.JButton();
        BtnAgregarBebida = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        BtnRegresar = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();

        DialogoMensajeExito.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        DialogoMensajeExito.setTitle("Mensaje");
        DialogoMensajeExito.setBackground(new java.awt.Color(47, 20, 0));
        DialogoMensajeExito.setBounds(new java.awt.Rectangle(0, 0, 368, 152));
        DialogoMensajeExito.setMinimumSize(new java.awt.Dimension(368, 152));
        DialogoMensajeExito.setResizable(false);

        jPanel3.setBackground(new java.awt.Color(47, 20, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 153)));

        LblMensajeConfirmacion.setFont(new java.awt.Font("AppleGothic", 0, 16)); // NOI18N
        LblMensajeConfirmacion.setForeground(new java.awt.Color(255, 255, 102));
        LblMensajeConfirmacion.setText("Agregado a la Orden");

        BtnAceptarMensajeExito.setBackground(new java.awt.Color(255, 255, 153));
        BtnAceptarMensajeExito.setFont(new java.awt.Font("AppleGothic", 0, 16)); // NOI18N
        BtnAceptarMensajeExito.setForeground(new java.awt.Color(47, 20, 0));
        BtnAceptarMensajeExito.setText("Aceptar");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/checked.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LblMensajeConfirmacion))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(BtnAceptarMensajeExito)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(LblMensajeConfirmacion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnAceptarMensajeExito)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DialogoMensajeExitoLayout = new javax.swing.GroupLayout(DialogoMensajeExito.getContentPane());
        DialogoMensajeExito.getContentPane().setLayout(DialogoMensajeExitoLayout);
        DialogoMensajeExitoLayout.setHorizontalGroup(
            DialogoMensajeExitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DialogoMensajeExitoLayout.setVerticalGroup(
            DialogoMensajeExitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        DialogoMensajeError.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        DialogoMensajeError.setTitle("Mensaje de error");
        DialogoMensajeError.setBackground(new java.awt.Color(47, 20, 0));
        DialogoMensajeError.setBounds(new java.awt.Rectangle(0, 0, 373, 155));
        DialogoMensajeError.setMinimumSize(new java.awt.Dimension(373, 155));
        DialogoMensajeError.setResizable(false);

        jPanel6.setBackground(new java.awt.Color(47, 20, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 102)));
        jPanel6.setMinimumSize(new java.awt.Dimension(434, 143));
        jPanel6.setPreferredSize(new java.awt.Dimension(434, 143));

        LbllMensajeError.setFont(new java.awt.Font("AppleGothic", 0, 16)); // NOI18N
        LbllMensajeError.setForeground(new java.awt.Color(255, 255, 102));
        LbllMensajeError.setText("Error: Campos Vacíos");

        BtnAceptarMensajeErrores.setBackground(new java.awt.Color(255, 255, 153));
        BtnAceptarMensajeErrores.setFont(new java.awt.Font("AppleGothic", 0, 16)); // NOI18N
        BtnAceptarMensajeErrores.setForeground(new java.awt.Color(51, 0, 0));
        BtnAceptarMensajeErrores.setText("Aceptar");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnAceptarMensajeErrores)
                    .addComponent(LbllMensajeError, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(LbllMensajeError)
                        .addGap(18, 18, 18)
                        .addComponent(BtnAceptarMensajeErrores))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DialogoMensajeErrorLayout = new javax.swing.GroupLayout(DialogoMensajeError.getContentPane());
        DialogoMensajeError.getContentPane().setLayout(DialogoMensajeErrorLayout);
        DialogoMensajeErrorLayout.setHorizontalGroup(
            DialogoMensajeErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 373, Short.MAX_VALUE)
        );
        DialogoMensajeErrorLayout.setVerticalGroup(
            DialogoMensajeErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar a la Orden - Cafezito");
        setResizable(false);

        jPanel22.setBackground(new java.awt.Color(47, 20, 0));

        jPanel26.setBackground(new java.awt.Color(47, 20, 0));
        jPanel26.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Agregar por Código", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monotype Corsiva", 0, 24), new java.awt.Color(255, 255, 204))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 102));
        jLabel22.setText("Código Menú:");

        jLabel30.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 102));
        jLabel30.setText("Cantidad:");

        SpinnerCantidadCodMenu.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        SpinnerCantidadCodMenu.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));

        TxtCodigoMenu.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        BtnAgregarCodigoMenu.setBackground(new java.awt.Color(193, 65, 0));
        BtnAgregarCodigoMenu.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        BtnAgregarCodigoMenu.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgregarCodigoMenu.setText("Agregar");

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtCodigoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SpinnerCantidadCodMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnAgregarCodigoMenu)
                .addGap(42, 42, 42))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel30)
                    .addComponent(SpinnerCantidadCodMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCodigoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAgregarCodigoMenu))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jPanel27.setBackground(new java.awt.Color(179, 66, 7));

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logopeque.png"))); // NOI18N

        jPanel28.setBackground(new java.awt.Color(47, 20, 0));
        jPanel28.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Agregar por Categoría", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monotype Corsiva", 0, 24), new java.awt.Color(255, 255, 204))); // NOI18N

        jLabel44.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 102));
        jLabel44.setText("Platillo:");

        jLabel45.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Cantidad:");

        SpinnerCantidadPlatillo.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        SpinnerCantidadPlatillo.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));

        BtnAgregarPlatillo.setBackground(new java.awt.Color(193, 65, 0));
        BtnAgregarPlatillo.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        BtnAgregarPlatillo.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgregarPlatillo.setText("Agregar");

        jLabel46.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 102));
        jLabel46.setText("Bebida:");

        jLabel47.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 102));
        jLabel47.setText("Postre:");

        CbxPlatillo.setBackground(new java.awt.Color(255, 255, 204));
        CbxPlatillo.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        CbxPlatillo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nombre" }));

        CbxPostre.setBackground(new java.awt.Color(255, 255, 204));
        CbxPostre.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        CbxPostre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nombre" }));

        CbxBebida.setBackground(new java.awt.Color(255, 255, 204));
        CbxBebida.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        CbxBebida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nombre" }));

        SpinnerCantidadBebida.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        SpinnerCantidadBebida.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));

        SpinnerCantidadPostre.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        SpinnerCantidadPostre.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));

        BtnAgregarPostre.setBackground(new java.awt.Color(193, 65, 0));
        BtnAgregarPostre.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        BtnAgregarPostre.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgregarPostre.setText("Agregar");

        BtnAgregarBebida.setBackground(new java.awt.Color(193, 65, 0));
        BtnAgregarBebida.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        BtnAgregarBebida.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgregarBebida.setText("Agregar");

        jLabel48.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Tipo:");

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel28Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addComponent(jLabel47)
                        .addGap(18, 18, 18)
                        .addComponent(CbxPostre, 0, 209, Short.MAX_VALUE))
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel28Layout.createSequentialGroup()
                                .addComponent(jLabel44)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel28Layout.createSequentialGroup()
                                .addComponent(jLabel46)
                                .addGap(13, 13, 13)))
                        .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CbxPlatillo, 0, 209, Short.MAX_VALUE)
                            .addComponent(CbxBebida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addComponent(jLabel48)
                        .addGap(98, 98, 98)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SpinnerCantidadPlatillo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45)
                    .addComponent(SpinnerCantidadBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpinnerCantidadPostre, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnAgregarPlatillo)
                    .addComponent(BtnAgregarPostre)
                    .addComponent(BtnAgregarBebida))
                .addGap(42, 42, 42))
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(jLabel48))
                .addGap(7, 7, 7)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbxPlatillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44)
                    .addComponent(SpinnerCantidadPlatillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAgregarPlatillo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(CbxBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpinnerCantidadBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAgregarBebida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbxPostre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47)
                    .addComponent(SpinnerCantidadPostre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAgregarPostre))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        BtnRegresar.setBackground(new java.awt.Color(255, 255, 153));
        BtnRegresar.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        BtnRegresar.setForeground(new java.awt.Color(51, 0, 0));
        BtnRegresar.setText("Regresar");

        jLabel49.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 102));
        jLabel49.setText("Número de Orden: ");

        jLabel93.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bottomBanner.png"))); // NOI18N

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel43))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel22Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnRegresar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel49, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                    .addContainerGap(56, Short.MAX_VALUE)
                    .addComponent(jLabel93)
                    .addContainerGap(56, Short.MAX_VALUE)))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addComponent(jLabel43)
                .addGap(8, 8, 8)
                .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel49)
                .addGap(10, 10, 10)
                .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnRegresar)
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                    .addContainerGap(467, Short.MAX_VALUE)
                    .addComponent(jLabel93, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaAgregarAlaOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaAgregarAlaOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaAgregarAlaOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaAgregarAlaOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaAgregarAlaOrden().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnAceptarMensajeErrores;
    public javax.swing.JButton BtnAceptarMensajeExito;
    public javax.swing.JButton BtnAgregarBebida;
    public javax.swing.JButton BtnAgregarCodigoMenu;
    public javax.swing.JButton BtnAgregarPlatillo;
    public javax.swing.JButton BtnAgregarPostre;
    public javax.swing.JButton BtnRegresar;
    public javax.swing.JComboBox<String> CbxBebida;
    public javax.swing.JComboBox<String> CbxPlatillo;
    public javax.swing.JComboBox<String> CbxPostre;
    public javax.swing.JDialog DialogoMensajeError;
    public javax.swing.JDialog DialogoMensajeExito;
    public javax.swing.JLabel LblMensajeConfirmacion;
    public javax.swing.JLabel LbllMensajeError;
    public javax.swing.JSpinner SpinnerCantidadBebida;
    public javax.swing.JSpinner SpinnerCantidadCodMenu;
    public javax.swing.JSpinner SpinnerCantidadPlatillo;
    public javax.swing.JSpinner SpinnerCantidadPostre;
    public javax.swing.JTextField TxtCodigoMenu;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel43;
    public javax.swing.JLabel jLabel44;
    public javax.swing.JLabel jLabel45;
    public javax.swing.JLabel jLabel46;
    public javax.swing.JLabel jLabel47;
    public javax.swing.JLabel jLabel48;
    public javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JPanel jPanel22;
    public javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    public javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
