/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author YareMtz
 */
public class PantallaModificarEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form PaantallaModificarEmpleado
     */
    public PantallaModificarEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        DialogoMensajeError = new javax.swing.JDialog(this,true);
        jPanel6 = new javax.swing.JPanel();
        LbllMensajeError = new javax.swing.JLabel();
        BtnAceptarMensajeErrores = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel39 = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        TxtCodigoEmpleadoModificar = new javax.swing.JTextField();
        BtnBuscarModificar = new javax.swing.JButton();
        RbBtnNomEmpleadoModificar = new javax.swing.JRadioButton();
        RdBtnCodEmpleadoModificar = new javax.swing.JRadioButton();
        TxtNombreEmpleadoModificar = new javax.swing.JTextField();
        jPanel41 = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        jPanel42 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        TblEmpleadoModificar = new javax.swing.JTable();
        BtnModificarEmpleado = new javax.swing.JButton();
        BtnRegresarModificarEmpleado = new javax.swing.JButton();
        jLabel95 = new javax.swing.JLabel();

        DialogoMensajeError.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        DialogoMensajeError.setTitle("Mensaje de error");
        DialogoMensajeError.setBackground(new java.awt.Color(47, 20, 0));
        DialogoMensajeError.setBounds(new java.awt.Rectangle(0, 0, 373, 155));
        DialogoMensajeError.setMinimumSize(new java.awt.Dimension(373, 155));
        DialogoMensajeError.setResizable(false);

        jPanel6.setBackground(new java.awt.Color(47, 20, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204), 2));
        jPanel6.setBounds(new java.awt.Rectangle(0, 0, 321, 151));

        LbllMensajeError.setFont(new java.awt.Font("AppleGothic", 0, 16)); // NOI18N
        LbllMensajeError.setForeground(new java.awt.Color(255, 255, 102));
        LbllMensajeError.setText("Error: Campos Vacíos");

        BtnAceptarMensajeErrores.setBackground(new java.awt.Color(255, 255, 153));
        BtnAceptarMensajeErrores.setFont(new java.awt.Font("AppleGothic", 0, 16)); // NOI18N
        BtnAceptarMensajeErrores.setForeground(new java.awt.Color(51, 0, 0));
        BtnAceptarMensajeErrores.setText("Aceptar");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel7)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(BtnAceptarMensajeErrores))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(LbllMensajeError)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(LbllMensajeError)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnAceptarMensajeErrores)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DialogoMensajeErrorLayout = new javax.swing.GroupLayout(DialogoMensajeError.getContentPane());
        DialogoMensajeError.getContentPane().setLayout(DialogoMensajeErrorLayout);
        DialogoMensajeErrorLayout.setHorizontalGroup(
            DialogoMensajeErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DialogoMensajeErrorLayout.setVerticalGroup(
            DialogoMensajeErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Empleado");
        setResizable(false);

        jPanel39.setBackground(new java.awt.Color(47, 20, 0));

        jPanel40.setBackground(new java.awt.Color(47, 20, 0));
        jPanel40.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Buscar Por", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monotype Corsiva", 0, 24), new java.awt.Color(255, 255, 204))); // NOI18N

        TxtCodigoEmpleadoModificar.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        BtnBuscarModificar.setBackground(new java.awt.Color(255, 255, 153));
        BtnBuscarModificar.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        BtnBuscarModificar.setForeground(new java.awt.Color(51, 0, 0));
        BtnBuscarModificar.setText("Buscar");

        RbBtnNomEmpleadoModificar.setBackground(new java.awt.Color(47, 20, 0));
        buttonGroup1.add(RbBtnNomEmpleadoModificar);
        RbBtnNomEmpleadoModificar.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        RbBtnNomEmpleadoModificar.setForeground(new java.awt.Color(255, 255, 102));
        RbBtnNomEmpleadoModificar.setText("Nombre:");

        RdBtnCodEmpleadoModificar.setBackground(new java.awt.Color(47, 20, 0));
        buttonGroup1.add(RdBtnCodEmpleadoModificar);
        RdBtnCodEmpleadoModificar.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        RdBtnCodEmpleadoModificar.setForeground(new java.awt.Color(255, 255, 102));
        RdBtnCodEmpleadoModificar.setSelected(true);
        RdBtnCodEmpleadoModificar.setText("Código Empleado:");

        TxtNombreEmpleadoModificar.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        TxtNombreEmpleadoModificar.setEnabled(false);

        javax.swing.GroupLayout jPanel40Layout = new javax.swing.GroupLayout(jPanel40);
        jPanel40.setLayout(jPanel40Layout);
        jPanel40Layout.setHorizontalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel40Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RdBtnCodEmpleadoModificar)
                    .addComponent(RbBtnNomEmpleadoModificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtCodigoEmpleadoModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(TxtNombreEmpleadoModificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnBuscarModificar)
                .addGap(22, 22, 22))
        );
        jPanel40Layout.setVerticalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel40Layout.createSequentialGroup()
                .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel40Layout.createSequentialGroup()
                        .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtCodigoEmpleadoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RdBtnCodEmpleadoModificar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RbBtnNomEmpleadoModificar)
                            .addComponent(TxtNombreEmpleadoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel40Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(BtnBuscarModificar)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel41.setBackground(new java.awt.Color(179, 66, 7));

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );

        jLabel73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logopeque.png"))); // NOI18N

        jPanel42.setBackground(new java.awt.Color(47, 20, 0));
        jPanel42.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Resultados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monotype Corsiva", 0, 24), new java.awt.Color(255, 255, 204))); // NOI18N

        TblEmpleadoModificar.setBackground(new java.awt.Color(255, 255, 153));
        TblEmpleadoModificar.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        TblEmpleadoModificar.setForeground(new java.awt.Color(51, 0, 0));
        TblEmpleadoModificar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Apellido Paterno", "Apellido Materno"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(TblEmpleadoModificar);

        BtnModificarEmpleado.setBackground(new java.awt.Color(255, 255, 153));
        BtnModificarEmpleado.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        BtnModificarEmpleado.setForeground(new java.awt.Color(51, 0, 0));
        BtnModificarEmpleado.setText("Modificar");
        BtnModificarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel42Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                    .addGroup(jPanel42Layout.createSequentialGroup()
                        .addComponent(BtnModificarEmpleado)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel42Layout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(BtnModificarEmpleado)
                .addContainerGap())
        );

        BtnRegresarModificarEmpleado.setBackground(new java.awt.Color(255, 255, 153));
        BtnRegresarModificarEmpleado.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        BtnRegresarModificarEmpleado.setForeground(new java.awt.Color(51, 0, 0));
        BtnRegresarModificarEmpleado.setText("Regresar");

        jLabel95.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bottomBanner.png"))); // NOI18N

        javax.swing.GroupLayout jPanel39Layout = new javax.swing.GroupLayout(jPanel39);
        jPanel39.setLayout(jPanel39Layout);
        jPanel39Layout.setHorizontalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel39Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnRegresarModificarEmpleado)
                    .addGroup(jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel39Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel39Layout.createSequentialGroup()
                        .addComponent(jLabel73)
                        .addGap(129, 129, 129))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel39Layout.createSequentialGroup()
                        .addComponent(jLabel95)
                        .addGap(22, 22, 22))))
        );
        jPanel39Layout.setVerticalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel39Layout.createSequentialGroup()
                .addComponent(jLabel73)
                .addGap(8, 8, 8)
                .addComponent(jPanel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnRegresarModificarEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel95)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnModificarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnModificarEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaModificarEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnAceptarMensajeErrores;
    public javax.swing.JButton BtnBuscarModificar;
    public javax.swing.JButton BtnModificarEmpleado;
    public javax.swing.JButton BtnRegresarModificarEmpleado;
    public javax.swing.JDialog DialogoMensajeError;
    public javax.swing.JLabel LbllMensajeError;
    public javax.swing.JRadioButton RbBtnNomEmpleadoModificar;
    public javax.swing.JRadioButton RdBtnCodEmpleadoModificar;
    public javax.swing.JTable TblEmpleadoModificar;
    public javax.swing.JTextField TxtCodigoEmpleadoModificar;
    public javax.swing.JTextField TxtNombreEmpleadoModificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane7;
    // End of variables declaration//GEN-END:variables
}
