/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Alexis Salvador
 */
public class PantallaModificarOrden extends javax.swing.JFrame {

    /**
     * Creates new form PantallaModificarOrden
     */
    public PantallaModificarOrden() {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/icon_cafezito.png"));
        setIconImage(icon);
        TblModOrden.getTableHeader().setReorderingAllowed(false);
        TblModOrdenTotal.getTableHeader().setReorderingAllowed(false);
        PantallaModificarCantidad.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PantallaModificarCantidad = new javax.swing.JDialog(this,true);
        jPanel1 = new javax.swing.JPanel();
        BtnRegresar = new javax.swing.JButton();
        jPanel26 = new javax.swing.JPanel();
        SpinnerModificarCantidad = new javax.swing.JSpinner();
        LblPlatillo = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        BtnModificarAceptar = new javax.swing.JButton();
        DialogoPregunta = new javax.swing.JDialog(this,true);
        jPanel4 = new javax.swing.JPanel();
        LblPreguntaensaje = new javax.swing.JLabel();
        jBtnActualizarno = new javax.swing.JButton();
        jBtnActualizarsi = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        DialogoMensajeExito = new javax.swing.JDialog(this,true);
        jPanel3 = new javax.swing.JPanel();
        LblMensajeConfirmacion = new javax.swing.JLabel();
        BtnAceptarMensajeExito = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        DialogoMensajeError = new javax.swing.JDialog(this,true);
        jPanel6 = new javax.swing.JPanel();
        LbllMensajeError = new javax.swing.JLabel();
        BtnAceptarMensajeErrores = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        CbxNumeroMesaModOrden = new javax.swing.JComboBox<>();
        TxtNumeroOrden = new javax.swing.JTextField();
        BtnBuscarModOrden = new javax.swing.JButton();
        RbtnNumMesa = new javax.swing.JRadioButton();
        RbtnNumOrden = new javax.swing.JRadioButton();
        jPanel23 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TblModOrden = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        TblModOrdenTotal = new javax.swing.JTable();
        BtnAgregarModOrden = new javax.swing.JButton();
        BtnModificarModOrden = new javax.swing.JButton();
        BtnEliminarModOrden = new javax.swing.JButton();
        BtnRegresarModOrden = new javax.swing.JButton();
        BtnGuardarModOrden = new javax.swing.JButton();
        jLabel94 = new javax.swing.JLabel();

        PantallaModificarCantidad.setMinimumSize(new java.awt.Dimension(358, 195));
        PantallaModificarCantidad.setPreferredSize(new java.awt.Dimension(358, 195));
        PantallaModificarCantidad.setSize(new java.awt.Dimension(358, 195));

        jPanel1.setBackground(new java.awt.Color(47, 20, 0));

        BtnRegresar.setBackground(new java.awt.Color(255, 255, 153));
        BtnRegresar.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        BtnRegresar.setForeground(new java.awt.Color(51, 0, 0));
        BtnRegresar.setText("Regresar");

        jPanel26.setBackground(new java.awt.Color(47, 20, 0));
        jPanel26.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Modificar Cantidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monotype Corsiva", 0, 24), new java.awt.Color(255, 255, 204))); // NOI18N

        SpinnerModificarCantidad.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        SpinnerModificarCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));

        LblPlatillo.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        LblPlatillo.setForeground(new java.awt.Color(255, 255, 102));
        LblPlatillo.setText("Nombre:");

        jLabel30.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 102));
        jLabel30.setText("Cantidad:");

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblPlatillo)
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SpinnerModificarCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addComponent(LblPlatillo)
                .addGap(11, 11, 11)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpinnerModificarCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        BtnModificarAceptar.setBackground(new java.awt.Color(193, 65, 0));
        BtnModificarAceptar.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        BtnModificarAceptar.setForeground(new java.awt.Color(255, 255, 255));
        BtnModificarAceptar.setText("Aceptar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnModificarAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnRegresar)
                .addGap(68, 68, 68))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnModificarAceptar)
                    .addComponent(BtnRegresar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PantallaModificarCantidadLayout = new javax.swing.GroupLayout(PantallaModificarCantidad.getContentPane());
        PantallaModificarCantidad.getContentPane().setLayout(PantallaModificarCantidadLayout);
        PantallaModificarCantidadLayout.setHorizontalGroup(
            PantallaModificarCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PantallaModificarCantidadLayout.setVerticalGroup(
            PantallaModificarCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        DialogoPregunta.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        DialogoPregunta.setTitle("Mensaje de confirmación");
        DialogoPregunta.setBackground(new java.awt.Color(47, 20, 0));
        DialogoPregunta.setBounds(new java.awt.Rectangle(0, 0, 387, 152));
        DialogoPregunta.setMinimumSize(new java.awt.Dimension(387, 152));
        DialogoPregunta.setResizable(false);

        jPanel4.setBackground(new java.awt.Color(47, 20, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204), 2));

        LblPreguntaensaje.setFont(new java.awt.Font("AppleGothic", 0, 16)); // NOI18N
        LblPreguntaensaje.setForeground(new java.awt.Color(255, 255, 102));
        LblPreguntaensaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/question.png"))); // NOI18N
        LblPreguntaensaje.setText("¿Desea actualizar la cantidad?");

        jBtnActualizarno.setBackground(new java.awt.Color(255, 255, 153));
        jBtnActualizarno.setFont(new java.awt.Font("AppleGothic", 0, 16)); // NOI18N
        jBtnActualizarno.setForeground(new java.awt.Color(47, 20, 0));
        jBtnActualizarno.setText("No");

        jBtnActualizarsi.setBackground(new java.awt.Color(255, 255, 153));
        jBtnActualizarsi.setFont(new java.awt.Font("AppleGothic", 0, 16)); // NOI18N
        jBtnActualizarsi.setForeground(new java.awt.Color(47, 20, 0));
        jBtnActualizarsi.setText("Si");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jBtnActualizarsi, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jBtnActualizarno, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(LblPreguntaensaje)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(LblPreguntaensaje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnActualizarno)
                            .addComponent(jBtnActualizarsi))))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DialogoPreguntaLayout = new javax.swing.GroupLayout(DialogoPregunta.getContentPane());
        DialogoPregunta.getContentPane().setLayout(DialogoPreguntaLayout);
        DialogoPreguntaLayout.setHorizontalGroup(
            DialogoPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DialogoPreguntaLayout.setVerticalGroup(
            DialogoPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        DialogoMensajeExito.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        DialogoMensajeExito.setTitle("Mensaje");
        DialogoMensajeExito.setBackground(new java.awt.Color(47, 20, 0));
        DialogoMensajeExito.setBounds(new java.awt.Rectangle(0, 0, 368, 152));
        DialogoMensajeExito.setMinimumSize(new java.awt.Dimension(368, 152));
        DialogoMensajeExito.setResizable(false);

        jPanel3.setBackground(new java.awt.Color(47, 20, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204), 2));

        LblMensajeConfirmacion.setFont(new java.awt.Font("AppleGothic", 0, 16)); // NOI18N
        LblMensajeConfirmacion.setForeground(new java.awt.Color(255, 255, 102));
        LblMensajeConfirmacion.setText("La actualización se ha realizado con exito");

        BtnAceptarMensajeExito.setBackground(new java.awt.Color(255, 255, 153));
        BtnAceptarMensajeExito.setFont(new java.awt.Font("AppleGothic", 0, 16)); // NOI18N
        BtnAceptarMensajeExito.setForeground(new java.awt.Color(47, 20, 0));
        BtnAceptarMensajeExito.setText("Aceptar");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/checked.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblMensajeConfirmacion)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(BtnAceptarMensajeExito)
                        .addGap(139, 139, 139))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(LblMensajeConfirmacion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnAceptarMensajeExito)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DialogoMensajeExitoLayout = new javax.swing.GroupLayout(DialogoMensajeExito.getContentPane());
        DialogoMensajeExito.getContentPane().setLayout(DialogoMensajeExitoLayout);
        DialogoMensajeExitoLayout.setHorizontalGroup(
            DialogoMensajeExitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DialogoMensajeExitoLayout.setVerticalGroup(
            DialogoMensajeExitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        DialogoMensajeError.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        DialogoMensajeError.setTitle("Mensaje de error");
        DialogoMensajeError.setBackground(new java.awt.Color(47, 20, 0));
        DialogoMensajeError.setBounds(new java.awt.Rectangle(0, 0, 373, 155));
        DialogoMensajeError.setMinimumSize(new java.awt.Dimension(373, 155));
        DialogoMensajeError.setResizable(false);

        jPanel6.setBackground(new java.awt.Color(47, 20, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204), 2));

        LbllMensajeError.setFont(new java.awt.Font("AppleGothic", 0, 16)); // NOI18N
        LbllMensajeError.setForeground(new java.awt.Color(255, 255, 102));
        LbllMensajeError.setText("Error: Campos Vacíos");

        BtnAceptarMensajeErrores.setBackground(new java.awt.Color(255, 255, 153));
        BtnAceptarMensajeErrores.setFont(new java.awt.Font("AppleGothic", 0, 16)); // NOI18N
        BtnAceptarMensajeErrores.setForeground(new java.awt.Color(51, 0, 0));
        BtnAceptarMensajeErrores.setText("Aceptar");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel7)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(LbllMensajeError))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(BtnAceptarMensajeErrores)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(LbllMensajeError)
                        .addGap(18, 18, 18)
                        .addComponent(BtnAceptarMensajeErrores)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DialogoMensajeErrorLayout = new javax.swing.GroupLayout(DialogoMensajeError.getContentPane());
        DialogoMensajeError.getContentPane().setLayout(DialogoMensajeErrorLayout);
        DialogoMensajeErrorLayout.setHorizontalGroup(
            DialogoMensajeErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DialogoMensajeErrorLayout.setVerticalGroup(
            DialogoMensajeErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Orden - Cafezito");
        setResizable(false);

        jPanel20.setBackground(new java.awt.Color(47, 20, 0));
        jPanel20.setToolTipText("");

        jPanel21.setBackground(new java.awt.Color(47, 20, 0));
        jPanel21.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Buscar Por", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monotype Corsiva", 0, 24), new java.awt.Color(255, 255, 204))); // NOI18N

        CbxNumeroMesaModOrden.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        CbxNumeroMesaModOrden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        TxtNumeroOrden.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        TxtNumeroOrden.setEnabled(false);

        BtnBuscarModOrden.setBackground(new java.awt.Color(193, 65, 0));
        BtnBuscarModOrden.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        BtnBuscarModOrden.setForeground(new java.awt.Color(255, 255, 255));
        BtnBuscarModOrden.setText("Buscar");

        RbtnNumMesa.setBackground(new java.awt.Color(47, 20, 0));
        buttonGroup1.add(RbtnNumMesa);
        RbtnNumMesa.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        RbtnNumMesa.setForeground(new java.awt.Color(255, 255, 102));
        RbtnNumMesa.setSelected(true);
        RbtnNumMesa.setText("Número de Mesa:");

        RbtnNumOrden.setBackground(new java.awt.Color(47, 20, 0));
        buttonGroup1.add(RbtnNumOrden);
        RbtnNumOrden.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        RbtnNumOrden.setForeground(new java.awt.Color(255, 255, 102));
        RbtnNumOrden.setText("Número de Orden:");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RbtnNumMesa)
                    .addComponent(RbtnNumOrden))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CbxNumeroMesaModOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNumeroOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BtnBuscarModOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtNumeroOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RbtnNumOrden))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CbxNumeroMesaModOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RbtnNumMesa)))
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnBuscarModOrden)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel23.setBackground(new java.awt.Color(179, 66, 7));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logopeque.png"))); // NOI18N

        jPanel25.setBackground(new java.awt.Color(47, 20, 0));
        jPanel25.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Datos de la Orden", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monotype Corsiva", 0, 24), new java.awt.Color(255, 255, 204))); // NOI18N

        TblModOrden.setBackground(new java.awt.Color(255, 255, 153));
        TblModOrden.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        TblModOrden.setForeground(new java.awt.Color(51, 0, 0));
        TblModOrden.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Cantidad", "Precio", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(TblModOrden);

        TblModOrdenTotal.setBackground(new java.awt.Color(255, 255, 153));
        TblModOrdenTotal.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        TblModOrdenTotal.setForeground(new java.awt.Color(51, 0, 0));
        TblModOrdenTotal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(TblModOrdenTotal);

        BtnAgregarModOrden.setBackground(new java.awt.Color(193, 65, 0));
        BtnAgregarModOrden.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        BtnAgregarModOrden.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgregarModOrden.setText("Agregar");
        BtnAgregarModOrden.setEnabled(false);

        BtnModificarModOrden.setBackground(new java.awt.Color(193, 65, 0));
        BtnModificarModOrden.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        BtnModificarModOrden.setForeground(new java.awt.Color(255, 255, 255));
        BtnModificarModOrden.setText("Modificar");
        BtnModificarModOrden.setEnabled(false);

        BtnEliminarModOrden.setBackground(new java.awt.Color(193, 65, 0));
        BtnEliminarModOrden.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        BtnEliminarModOrden.setForeground(new java.awt.Color(255, 255, 255));
        BtnEliminarModOrden.setText("Eliminar");
        BtnEliminarModOrden.setEnabled(false);

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addComponent(BtnAgregarModOrden)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnModificarModOrden)
                        .addGap(18, 18, 18)
                        .addComponent(BtnEliminarModOrden)
                        .addGap(169, 169, 169)))
                .addContainerGap())
            .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel25Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane5)
                    .addContainerGap()))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAgregarModOrden)
                    .addComponent(BtnEliminarModOrden)
                    .addComponent(BtnModificarModOrden))
                .addGap(0, 17, Short.MAX_VALUE))
            .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel25Layout.createSequentialGroup()
                    .addGap(91, 91, 91)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(58, Short.MAX_VALUE)))
        );

        BtnRegresarModOrden.setBackground(new java.awt.Color(255, 255, 153));
        BtnRegresarModOrden.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        BtnRegresarModOrden.setForeground(new java.awt.Color(51, 0, 0));
        BtnRegresarModOrden.setText("Regresar");

        BtnGuardarModOrden.setBackground(new java.awt.Color(255, 255, 153));
        BtnGuardarModOrden.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        BtnGuardarModOrden.setForeground(new java.awt.Color(51, 0, 0));
        BtnGuardarModOrden.setText("Guardar");
        BtnGuardarModOrden.setEnabled(false);

        jLabel94.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bottomBanner.png"))); // NOI18N

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(BtnGuardarModOrden)
                        .addGap(18, 18, 18)
                        .addComponent(BtnRegresarModOrden))
                    .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addGap(129, 129, 129))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel94)
                        .addGap(34, 34, 34))))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addComponent(jLabel42)
                .addGap(8, 8, 8)
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnRegresarModOrden)
                    .addComponent(BtnGuardarModOrden))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel94, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaModificarOrden().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnAceptarMensajeErrores;
    public javax.swing.JButton BtnAceptarMensajeExito;
    public javax.swing.JButton BtnAgregarModOrden;
    public javax.swing.JButton BtnBuscarModOrden;
    public javax.swing.JButton BtnEliminarModOrden;
    public javax.swing.JButton BtnGuardarModOrden;
    public javax.swing.JButton BtnModificarAceptar;
    public javax.swing.JButton BtnModificarModOrden;
    public javax.swing.JButton BtnRegresar;
    public javax.swing.JButton BtnRegresarModOrden;
    public javax.swing.JComboBox<String> CbxNumeroMesaModOrden;
    public javax.swing.JDialog DialogoMensajeError;
    public javax.swing.JDialog DialogoMensajeExito;
    public javax.swing.JDialog DialogoPregunta;
    public javax.swing.JLabel LblMensajeConfirmacion;
    public javax.swing.JLabel LblPlatillo;
    private javax.swing.JLabel LblPreguntaensaje;
    public javax.swing.JLabel LbllMensajeError;
    public javax.swing.JDialog PantallaModificarCantidad;
    public javax.swing.JRadioButton RbtnNumMesa;
    public javax.swing.JRadioButton RbtnNumOrden;
    public javax.swing.JSpinner SpinnerModificarCantidad;
    public javax.swing.JTable TblModOrden;
    public javax.swing.JTable TblModOrdenTotal;
    public javax.swing.JTextField TxtNumeroOrden;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JButton jBtnActualizarno;
    public javax.swing.JButton jBtnActualizarsi;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel25;
    public javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    public javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
