/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Alexis Salvador
 */
public class PantallaLogin extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public PantallaLogin() {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/icon_cafezito.png"));
        setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogoMensajeExito = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        LbllMensajeBienvenido = new javax.swing.JLabel();
        BtnAceptarMensaje = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        DialogoMensajeError = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        LbllMensajeError = new javax.swing.JLabel();
        BtnAceptarMensajeError = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        BtnIniciarSesion = new javax.swing.JButton();
        TxtUsuario = new javax.swing.JTextField();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        TxtContrasenia = new javax.swing.JPasswordField();
        Fondo = new javax.swing.JLabel();

        DialogoMensajeExito.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        DialogoMensajeExito.setTitle("Mensaje");
        DialogoMensajeExito.setBackground(new java.awt.Color(47, 20, 0));
        DialogoMensajeExito.setBounds(new java.awt.Rectangle(0, 0, 388, 130));
        DialogoMensajeExito.setMinimumSize(new java.awt.Dimension(388, 130));
        DialogoMensajeExito.setResizable(false);
        DialogoMensajeExito.setSize(new java.awt.Dimension(388, 130));

        jPanel3.setBackground(new java.awt.Color(47, 20, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204), 2));
        jPanel3.setBounds(new java.awt.Rectangle(0, 0, 321, 151));

        LbllMensajeBienvenido.setFont(new java.awt.Font("AppleGothic", 0, 18)); // NOI18N
        LbllMensajeBienvenido.setForeground(new java.awt.Color(255, 255, 102));
        LbllMensajeBienvenido.setText("¡Bienvenido ");

        BtnAceptarMensaje.setBackground(new java.awt.Color(255, 255, 153));
        BtnAceptarMensaje.setFont(new java.awt.Font("AppleGothic", 0, 18)); // NOI18N
        BtnAceptarMensaje.setForeground(new java.awt.Color(51, 0, 0));
        BtnAceptarMensaje.setText("Aceptar");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/man.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(LbllMensajeBienvenido))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(BtnAceptarMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(LbllMensajeBienvenido)
                        .addGap(12, 12, 12)
                        .addComponent(BtnAceptarMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DialogoMensajeExitoLayout = new javax.swing.GroupLayout(DialogoMensajeExito.getContentPane());
        DialogoMensajeExito.getContentPane().setLayout(DialogoMensajeExitoLayout);
        DialogoMensajeExitoLayout.setHorizontalGroup(
            DialogoMensajeExitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DialogoMensajeExitoLayout.setVerticalGroup(
            DialogoMensajeExitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        DialogoMensajeError.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        DialogoMensajeError.setTitle("Mensaje de error");
        DialogoMensajeError.setBackground(new java.awt.Color(47, 20, 0));
        DialogoMensajeError.setBounds(new java.awt.Rectangle(0, 0, 373, 155));
        DialogoMensajeError.setMinimumSize(new java.awt.Dimension(373, 155));
        DialogoMensajeError.setResizable(false);

        jPanel6.setBackground(new java.awt.Color(47, 20, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204), 2));
        jPanel6.setBounds(new java.awt.Rectangle(0, 0, 321, 151));

        LbllMensajeError.setFont(new java.awt.Font("AppleGothic", 0, 16)); // NOI18N
        LbllMensajeError.setForeground(new java.awt.Color(255, 255, 102));
        LbllMensajeError.setText("Error: Campos Vacíos");

        BtnAceptarMensajeError.setBackground(new java.awt.Color(255, 255, 153));
        BtnAceptarMensajeError.setFont(new java.awt.Font("AppleGothic", 0, 16)); // NOI18N
        BtnAceptarMensajeError.setForeground(new java.awt.Color(51, 0, 0));
        BtnAceptarMensajeError.setText("Aceptar");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel7)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(BtnAceptarMensajeError))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(LbllMensajeError)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(LbllMensajeError)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnAceptarMensajeError)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DialogoMensajeErrorLayout = new javax.swing.GroupLayout(DialogoMensajeError.getContentPane());
        DialogoMensajeError.getContentPane().setLayout(DialogoMensajeErrorLayout);
        DialogoMensajeErrorLayout.setHorizontalGroup(
            DialogoMensajeErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DialogoMensajeErrorLayout.setVerticalGroup(
            DialogoMensajeErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnIniciarSesion.setBackground(new java.awt.Color(255, 255, 153));
        BtnIniciarSesion.setFont(new java.awt.Font("AppleGothic", 0, 15)); // NOI18N
        BtnIniciarSesion.setForeground(new java.awt.Color(51, 0, 0));
        BtnIniciarSesion.setText("Iniciar Sesión");
        getContentPane().add(BtnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 260, 120, 30));

        TxtUsuario.setFont(new java.awt.Font("AppleGothic", 0, 15)); // NOI18N
        TxtUsuario.setForeground(new java.awt.Color(82, 34, 0));
        getContentPane().add(TxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 163, 160, 30));
        TxtUsuario.getAccessibleContext().setAccessibleName("");
        TxtUsuario.getAccessibleContext().setAccessibleDescription("");

        jLabel78.setFont(new java.awt.Font("AppleGothic", 0, 15)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(255, 255, 204));
        jLabel78.setText("Usuario:");
        getContentPane().add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        jLabel79.setFont(new java.awt.Font("AppleGothic", 0, 15)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(255, 255, 204));
        jLabel79.setText("Contraseña:");
        getContentPane().add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 90, -1));

        TxtContrasenia.setFont(new java.awt.Font("AppleGothic", 0, 15)); // NOI18N
        TxtContrasenia.setForeground(new java.awt.Color(82, 34, 0));
        getContentPane().add(TxtContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 160, 30));

        Fondo.setFont(new java.awt.Font("AppleGothic", 0, 15)); // NOI18N
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnAceptarMensaje;
    public javax.swing.JButton BtnAceptarMensajeError;
    public javax.swing.JButton BtnIniciarSesion;
    public javax.swing.JDialog DialogoMensajeError;
    public javax.swing.JDialog DialogoMensajeExito;
    public javax.swing.JLabel Fondo;
    public javax.swing.JLabel LbllMensajeBienvenido;
    public javax.swing.JLabel LbllMensajeError;
    public javax.swing.JPasswordField TxtContrasenia;
    public javax.swing.JTextField TxtUsuario;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel78;
    public javax.swing.JLabel jLabel79;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
