/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author YareMtz
 */
public class PantallaModificarDatosEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form PantallaModificarEmpleado
     */
    public PantallaModificarDatosEmpleado() {
        initComponents();
        DialogoActualizarEmpleado.setLocationRelativeTo(null);
        DialogoErrores.setLocationRelativeTo(null);
        DialogoMensajeError.setLocationRelativeTo(null);
        DialogoMensajeExito.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogoActualizarEmpleado = new javax.swing.JDialog(this,true);
        jPanel4 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jBtnActualizarno = new javax.swing.JButton();
        jBtnActualizarsi = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        DialogoMensajeExito = new javax.swing.JDialog(this,true);
        jPanel3 = new javax.swing.JPanel();
        LbllMensajeConfirmacion = new javax.swing.JLabel();
        BtnAceptarMensajeExito = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        DialogoErrores = new javax.swing.JDialog(this,true);
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLblErroresMenu = new javax.swing.JTextArea();
        BtnAceptarErroresMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DialogoMensajeError = new javax.swing.JDialog(this,true);
        jPanel6 = new javax.swing.JPanel();
        LbllMensajeError = new javax.swing.JLabel();
        BtnAceptarMensajeErrores = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        TxtNombreEmpleado = new javax.swing.JTextField();
        TxtApellidoMaternoEmpleado = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        TxtApellidoPaternoEmpleado = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        CbxDiaNacimientoEmpleado = new javax.swing.JComboBox<>();
        CbxMesNacimientoEmpleado = new javax.swing.JComboBox<>();
        CbxMesAñoEmpleado = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        TxtTelefonoEmpleado = new javax.swing.JTextField();
        TxtCelularEmplado = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        TxtColoniaEmpleado = new javax.swing.JTextField();
        TxtCalleEmpleado = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        TxtNumeroEmpleado = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        TxtCpDireccionEmpleado = new javax.swing.JTextField();
        jLabel80 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        BtnActualizarEmpleado = new javax.swing.JButton();
        BtnRegresarRegistrarEmpleado = new javax.swing.JButton();
        jPanel47 = new javax.swing.JPanel();
        jLabel81 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        CbxPuestoEmpleado = new javax.swing.JComboBox<>();
        TxtSueldoEmpleado = new javax.swing.JTextField();
        CbxStatusMod = new javax.swing.JComboBox<>();
        jLabel87 = new javax.swing.JLabel();
        jPanel49 = new javax.swing.JPanel();
        jLabel85 = new javax.swing.JLabel();
        TxtUsuarioEmpleado = new javax.swing.JTextField();
        txtContraseñaMod = new javax.swing.JPasswordField();
        TxtContraseñaRepMod = new javax.swing.JPasswordField();
        jLabel86 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        LblCodigoEmpleado = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        LblCodigoEmpleadoMod = new javax.swing.JLabel();

        DialogoActualizarEmpleado.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        DialogoActualizarEmpleado.setTitle("Mensaje de confirmación");
        DialogoActualizarEmpleado.setBackground(new java.awt.Color(47, 20, 0));
        DialogoActualizarEmpleado.setBounds(new java.awt.Rectangle(0, 0, 387, 152));
        DialogoActualizarEmpleado.setMinimumSize(new java.awt.Dimension(387, 152));
        DialogoActualizarEmpleado.setResizable(false);

        jPanel4.setBackground(new java.awt.Color(47, 20, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204), 2));

        jLabel45.setFont(new java.awt.Font("AppleGothic", 0, 16)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 102));
        jLabel45.setText("¿Desea actualizar el empleado?");

        jBtnActualizarno.setFont(new java.awt.Font("AppleGothic", 0, 16)); // NOI18N
        jBtnActualizarno.setText("No");

        jBtnActualizarsi.setFont(new java.awt.Font("AppleGothic", 0, 16)); // NOI18N
        jBtnActualizarsi.setText("Si");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/question.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jBtnActualizarsi, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jBtnActualizarno, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel45)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnActualizarno)
                            .addComponent(jBtnActualizarsi))))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DialogoActualizarEmpleadoLayout = new javax.swing.GroupLayout(DialogoActualizarEmpleado.getContentPane());
        DialogoActualizarEmpleado.getContentPane().setLayout(DialogoActualizarEmpleadoLayout);
        DialogoActualizarEmpleadoLayout.setHorizontalGroup(
            DialogoActualizarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DialogoActualizarEmpleadoLayout.setVerticalGroup(
            DialogoActualizarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        DialogoMensajeExito.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        DialogoMensajeExito.setTitle("Mensaje");
        DialogoMensajeExito.setBackground(new java.awt.Color(47, 20, 0));
        DialogoMensajeExito.setBounds(new java.awt.Rectangle(0, 0, 368, 152));
        DialogoMensajeExito.setMinimumSize(new java.awt.Dimension(368, 152));
        DialogoMensajeExito.setResizable(false);

        jPanel3.setBackground(new java.awt.Color(47, 20, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204), 2));
        jPanel3.setBounds(new java.awt.Rectangle(0, 0, 321, 151));

        LbllMensajeConfirmacion.setFont(new java.awt.Font("AppleGothic", 0, 16)); // NOI18N
        LbllMensajeConfirmacion.setForeground(new java.awt.Color(255, 255, 102));
        LbllMensajeConfirmacion.setText("La actualización se ha realizado con exito");

        BtnAceptarMensajeExito.setBackground(new java.awt.Color(255, 255, 153));
        BtnAceptarMensajeExito.setFont(new java.awt.Font("AppleGothic", 0, 16)); // NOI18N
        BtnAceptarMensajeExito.setForeground(new java.awt.Color(51, 0, 0));
        BtnAceptarMensajeExito.setText("Aceptar");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/checked.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LbllMensajeConfirmacion)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(BtnAceptarMensajeExito)
                        .addGap(139, 139, 139))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(LbllMensajeConfirmacion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnAceptarMensajeExito)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DialogoMensajeExitoLayout = new javax.swing.GroupLayout(DialogoMensajeExito.getContentPane());
        DialogoMensajeExito.getContentPane().setLayout(DialogoMensajeExitoLayout);
        DialogoMensajeExitoLayout.setHorizontalGroup(
            DialogoMensajeExitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DialogoMensajeExitoLayout.setVerticalGroup(
            DialogoMensajeExitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        DialogoErrores.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        DialogoErrores.setTitle("Mensaje de error");
        DialogoErrores.setBackground(new java.awt.Color(47, 20, 0));
        DialogoErrores.setBounds(new java.awt.Rectangle(0, 0, 399, 200));
        DialogoErrores.setMinimumSize(new java.awt.Dimension(399, 200));
        DialogoErrores.setResizable(false);

        jPanel5.setBackground(new java.awt.Color(47, 20, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204), 2));
        jPanel5.setMinimumSize(new java.awt.Dimension(395, 162));

        jLblErroresMenu.setEditable(false);
        jLblErroresMenu.setBackground(new java.awt.Color(47, 20, 0));
        jLblErroresMenu.setColumns(20);
        jLblErroresMenu.setFont(new java.awt.Font("AppleGothic", 0, 16)); // NOI18N
        jLblErroresMenu.setForeground(new java.awt.Color(255, 255, 153));
        jLblErroresMenu.setLineWrap(true);
        jLblErroresMenu.setRows(2);
        jLblErroresMenu.setToolTipText("");
        jLblErroresMenu.setBorder(null);
        jScrollPane1.setViewportView(jLblErroresMenu);

        BtnAceptarErroresMenu.setBackground(new java.awt.Color(255, 255, 153));
        BtnAceptarErroresMenu.setFont(new java.awt.Font("AppleGothic", 0, 18)); // NOI18N
        BtnAceptarErroresMenu.setForeground(new java.awt.Color(51, 0, 0));
        BtnAceptarErroresMenu.setText("Aceptar");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("AppleGothic", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 153));
        jLabel2.setText("Verificar datos del empleado:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(BtnAceptarErroresMenu)
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(78, 78, 78))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnAceptarErroresMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout DialogoErroresLayout = new javax.swing.GroupLayout(DialogoErrores.getContentPane());
        DialogoErrores.getContentPane().setLayout(DialogoErroresLayout);
        DialogoErroresLayout.setHorizontalGroup(
            DialogoErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogoErroresLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        DialogoErroresLayout.setVerticalGroup(
            DialogoErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        DialogoMensajeError.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        DialogoMensajeError.setTitle("Mensaje de error");
        DialogoMensajeError.setBackground(new java.awt.Color(47, 20, 0));
        DialogoMensajeError.setBounds(new java.awt.Rectangle(0, 0, 373, 155));
        DialogoMensajeError.setMinimumSize(new java.awt.Dimension(373, 155));
        DialogoMensajeError.setResizable(false);

        jPanel6.setBackground(new java.awt.Color(47, 20, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204), 2));
        jPanel6.setBounds(new java.awt.Rectangle(0, 0, 321, 151));

        LbllMensajeError.setFont(new java.awt.Font("AppleGothic", 0, 16)); // NOI18N
        LbllMensajeError.setForeground(new java.awt.Color(255, 255, 102));
        LbllMensajeError.setText("Error: Campos Vacíos");

        BtnAceptarMensajeErrores.setBackground(new java.awt.Color(255, 255, 153));
        BtnAceptarMensajeErrores.setFont(new java.awt.Font("AppleGothic", 0, 16)); // NOI18N
        BtnAceptarMensajeErrores.setForeground(new java.awt.Color(51, 0, 0));
        BtnAceptarMensajeErrores.setText("Aceptar");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel7)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(BtnAceptarMensajeErrores))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(LbllMensajeError)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(LbllMensajeError)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnAceptarMensajeErrores)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DialogoMensajeErrorLayout = new javax.swing.GroupLayout(DialogoMensajeError.getContentPane());
        DialogoMensajeError.getContentPane().setLayout(DialogoMensajeErrorLayout);
        DialogoMensajeErrorLayout.setHorizontalGroup(
            DialogoMensajeErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DialogoMensajeErrorLayout.setVerticalGroup(
            DialogoMensajeErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Datos del Empleado");
        setResizable(false);

        jPanel8.setBackground(new java.awt.Color(47, 20, 0));

        jPanel9.setBackground(new java.awt.Color(47, 20, 0));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Datos Personales Empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monotype Corsiva", 0, 24), new java.awt.Color(255, 255, 204))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 102));
        jLabel8.setText("* Apellido Paterno:");

        TxtNombreEmpleado.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        TxtApellidoMaternoEmpleado.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 102));
        jLabel23.setText("* Apellido Materno:");

        TxtApellidoPaternoEmpleado.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("* Fecha de Nacimiento:");

        CbxDiaNacimientoEmpleado.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        CbxDiaNacimientoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        CbxMesNacimientoEmpleado.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        CbxMesNacimientoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        CbxMesAñoEmpleado.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 102));
        jLabel25.setText("Mes:");

        jLabel26.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 102));
        jLabel26.setText("Día:");

        jLabel27.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 102));
        jLabel27.setText("Año:");

        jLabel28.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 102));
        jLabel28.setText("Teléfono:");

        jLabel29.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 102));
        jLabel29.setText("* Celular:");

        TxtTelefonoEmpleado.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        TxtCelularEmplado.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        jLabel32.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 102));
        jLabel32.setText("Número:");

        TxtColoniaEmpleado.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        TxtCalleEmpleado.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        jLabel33.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 102));
        jLabel33.setText("C.P:");

        jLabel34.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 102));
        jLabel34.setText("Calle:");

        TxtNumeroEmpleado.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        jLabel35.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 102));
        jLabel35.setText("Colonia:");

        TxtCpDireccionEmpleado.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        jLabel80.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(255, 255, 102));
        jLabel80.setText("* Nombre(s):");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel23)
                            .addComponent(jLabel80, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TxtApellidoPaternoEmpleado)
                            .addComponent(TxtApellidoMaternoEmpleado)
                            .addComponent(TxtNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel24)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addGap(101, 101, 101)
                            .addComponent(jLabel27)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(CbxMesAñoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel25)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(CbxMesNacimientoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel26)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(CbxDiaNacimientoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addGap(61, 61, 61)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel28)
                                        .addComponent(jLabel34))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel9Layout.createSequentialGroup()
                                            .addComponent(TxtTelefonoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel29)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TxtCelularEmplado, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(TxtCalleEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel32)
                                        .addComponent(jLabel35))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TxtColoniaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel9Layout.createSequentialGroup()
                                            .addComponent(TxtNumeroEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel33)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(TxtCpDireccionEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel80))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TxtApellidoPaternoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(TxtApellidoMaternoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CbxDiaNacimientoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel27)
                        .addComponent(CbxMesAñoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25)
                        .addComponent(CbxMesNacimientoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(TxtCelularEmplado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtTelefonoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(TxtCalleEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(TxtColoniaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(TxtNumeroEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(TxtCpDireccionEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel13.setBackground(new java.awt.Color(179, 66, 7));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logopeque.png"))); // NOI18N

        BtnActualizarEmpleado.setBackground(new java.awt.Color(255, 255, 153));
        BtnActualizarEmpleado.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        BtnActualizarEmpleado.setForeground(new java.awt.Color(51, 0, 0));
        BtnActualizarEmpleado.setText("Actualizar");

        BtnRegresarRegistrarEmpleado.setBackground(new java.awt.Color(255, 255, 153));
        BtnRegresarRegistrarEmpleado.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        BtnRegresarRegistrarEmpleado.setForeground(new java.awt.Color(51, 0, 0));
        BtnRegresarRegistrarEmpleado.setText("Regresar");

        jPanel47.setBackground(new java.awt.Color(47, 20, 0));
        jPanel47.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monotype Corsiva", 0, 24), new java.awt.Color(255, 255, 204))); // NOI18N

        jLabel81.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(255, 255, 102));
        jLabel81.setText("* Sueldo:");

        jLabel83.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(255, 255, 102));
        jLabel83.setText("* Puesto:");

        CbxPuestoEmpleado.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        CbxPuestoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "Mesero", "Cajero", "Contador", "Cocinero" }));

        TxtSueldoEmpleado.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        CbxStatusMod.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        CbxStatusMod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        jLabel87.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel87.setForeground(new java.awt.Color(255, 255, 102));
        jLabel87.setText("Estatus:");

        javax.swing.GroupLayout jPanel47Layout = new javax.swing.GroupLayout(jPanel47);
        jPanel47.setLayout(jPanel47Layout);
        jPanel47Layout.setHorizontalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel47Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel47Layout.createSequentialGroup()
                        .addComponent(jLabel87)
                        .addGap(18, 18, 18)
                        .addComponent(CbxStatusMod, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel47Layout.createSequentialGroup()
                        .addComponent(jLabel81)
                        .addGap(18, 18, 18)
                        .addComponent(TxtSueldoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel47Layout.createSequentialGroup()
                        .addComponent(jLabel83)
                        .addGap(18, 18, 18)
                        .addComponent(CbxPuestoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel47Layout.setVerticalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel47Layout.createSequentialGroup()
                .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel83)
                    .addComponent(CbxPuestoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtSueldoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel81))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel87)
                    .addComponent(CbxStatusMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel49.setBackground(new java.awt.Color(47, 20, 0));
        jPanel49.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Datos Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monotype Corsiva", 0, 24), new java.awt.Color(255, 255, 204))); // NOI18N

        jLabel85.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(255, 255, 102));
        jLabel85.setText("Usuario:");

        TxtUsuarioEmpleado.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        jLabel86.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(255, 255, 102));
        jLabel86.setText("Repetir Contraseña:");

        jLabel84.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(255, 255, 102));
        jLabel84.setText("Contraseña:");

        javax.swing.GroupLayout jPanel49Layout = new javax.swing.GroupLayout(jPanel49);
        jPanel49.setLayout(jPanel49Layout);
        jPanel49Layout.setHorizontalGroup(
            jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel49Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel84, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel86, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel85, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtUsuarioEmpleado)
                    .addComponent(txtContraseñaMod, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtContraseñaRepMod, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel49Layout.setVerticalGroup(
            jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel49Layout.createSequentialGroup()
                .addGroup(jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel85)
                    .addComponent(TxtUsuarioEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtContraseñaMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel84))
                .addGap(5, 5, 5)
                .addGroup(jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtContraseñaRepMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel86))
                .addContainerGap())
        );

        LblCodigoEmpleado.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        LblCodigoEmpleado.setForeground(new java.awt.Color(255, 255, 102));
        LblCodigoEmpleado.setText("Código Empleado:");

        jLabel97.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bottomBanner.png"))); // NOI18N

        LblCodigoEmpleadoMod.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        LblCodigoEmpleadoMod.setForeground(new java.awt.Color(255, 255, 102));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnActualizarEmpleado)
                            .addGap(18, 18, 18)
                            .addComponent(BtnRegresarRegistrarEmpleado))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(jPanel47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(1, 1, 1)
                                    .addComponent(jPanel49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(LblCodigoEmpleado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LblCodigoEmpleadoMod, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(183, 183, 183))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                    .addContainerGap(55, Short.MAX_VALUE)
                    .addComponent(jLabel97)
                    .addContainerGap(55, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(2, 2, 2)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LblCodigoEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblCodigoEmpleadoMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnActualizarEmpleado)
                    .addComponent(BtnRegresarRegistrarEmpleado))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                    .addGap(0, 609, Short.MAX_VALUE)
                    .addComponent(jLabel97)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarDatosEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarDatosEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarDatosEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarDatosEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaModificarDatosEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnAceptarErroresMenu;
    public javax.swing.JButton BtnAceptarMensajeErrores;
    public javax.swing.JButton BtnAceptarMensajeExito;
    public javax.swing.JButton BtnActualizarEmpleado;
    public javax.swing.JButton BtnRegresarRegistrarEmpleado;
    public javax.swing.JComboBox<String> CbxDiaNacimientoEmpleado;
    public javax.swing.JComboBox<String> CbxMesAñoEmpleado;
    public javax.swing.JComboBox<String> CbxMesNacimientoEmpleado;
    public javax.swing.JComboBox<String> CbxPuestoEmpleado;
    public javax.swing.JComboBox<String> CbxStatusMod;
    public javax.swing.JDialog DialogoActualizarEmpleado;
    public javax.swing.JDialog DialogoErrores;
    public javax.swing.JDialog DialogoMensajeError;
    public javax.swing.JDialog DialogoMensajeExito;
    public javax.swing.JLabel LblCodigoEmpleado;
    public javax.swing.JLabel LblCodigoEmpleadoMod;
    public javax.swing.JLabel LbllMensajeConfirmacion;
    public javax.swing.JLabel LbllMensajeError;
    public javax.swing.JTextField TxtApellidoMaternoEmpleado;
    public javax.swing.JTextField TxtApellidoPaternoEmpleado;
    public javax.swing.JTextField TxtCalleEmpleado;
    public javax.swing.JTextField TxtCelularEmplado;
    public javax.swing.JTextField TxtColoniaEmpleado;
    public javax.swing.JPasswordField TxtContraseñaRepMod;
    public javax.swing.JTextField TxtCpDireccionEmpleado;
    public javax.swing.JTextField TxtNombreEmpleado;
    public javax.swing.JTextField TxtNumeroEmpleado;
    public javax.swing.JTextField TxtSueldoEmpleado;
    public javax.swing.JTextField TxtTelefonoEmpleado;
    public javax.swing.JTextField TxtUsuarioEmpleado;
    public javax.swing.JButton jBtnActualizarno;
    public javax.swing.JButton jBtnActualizarsi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    public javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    public javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    public javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel32;
    public javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel97;
    public javax.swing.JTextArea jLblErroresMenu;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JPasswordField txtContraseñaMod;
    // End of variables declaration//GEN-END:variables
}
